name: PR

on:
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  lint-and-tests:
    name: Linting and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f #v2.35.5
        with:
          php-version: '8.3'
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies with composer
        run: composer install --no-ansi --no-interaction --no-progress

      - name: Linting (PHPCS)
        run: composer run phpcs

      - name: Run tests with phpunit/phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 #v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      ## TODO: Automatically deploy to dev environment

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: bcgov/action-builder-ghcr@fd17bc1cbb16a60514e0df3966d42dff9fc232bc #v4.0.0
        with:
          package: naad-connector
          build_context: .
          tags: |
            dev
            ${{ github.event.number }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 #v0.33.1
        with:
          image-ref: 'ghcr.io/bcgov/naad-connector/naad-connector:${{ github.event.number }}'
          output: 'trivy-results.sarif'
          trivy-config: '.github/trivy.yml'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'